-- MySQL Script generated by MySQL Workbench
-- Fri Sep 27 10:27:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peliculas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `peliculas`;
CREATE SCHEMA IF NOT EXISTS `peliculas` DEFAULT CHARACTER SET utf8mb4;
USE `peliculas`;

-- -----------------------------------------------------
-- Table `abonado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `abonado`;
CREATE TABLE IF NOT EXISTS `abonado` (
  `premium` TINYINT NOT NULL,
  `plan` VARCHAR(45) NULL,
  PRIMARY KEY (`premium`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias`;
CREATE TABLE IF NOT EXISTS `categorias` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `tipo` ENUM('web', 'panel') NULL DEFAULT 'web',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id` USING BTREE ON `categorias` (`id`);
-- ----------------------------
-- Records of categorias
-- ----------------------------
INSERT INTO `categorias` VALUES ('1', 'terror', 'web');
INSERT INTO `categorias` VALUES ('2', 'acción', 'web');
INSERT INTO `categorias` VALUES ('3', 'infantiles', 'web');
INSERT INTO `categorias` VALUES ('4', 'categorias', 'panel');
INSERT INTO `categorias` VALUES ('5', 'películas', 'panel');
INSERT INTO `categorias` VALUES ('6', 'perfil', 'panel');


-- -----------------------------------------------------
-- Table `peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculas`;
CREATE TABLE IF NOT EXISTS `peliculas` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `director` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_alta` DATETIME NULL DEFAULT NULL,
  `actores` VARCHAR(255) NULL DEFAULT NULL,
  `sinopsis` VARCHAR(255) NULL DEFAULT NULL,
  `categorias_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id` USING BTREE ON `peliculas` (`id`);

-- ----------------------------
-- Records of peliculas
-- ----------------------------
INSERT INTO `peliculas` VALUES ('1', 'SAW II', 'Darren Lynn Bousman', '2017-05-18 09:50:20', 'Donnie Wahlberg, Beverley Mitchell, Franky G | See full cast & crew', 'A detective and his team must rescue eight people trapped in a factory by the twisted serial killer known as Jigsaw.', '1', 'img/sawii.jpg');
INSERT INTO `peliculas` VALUES ('2', 'El juego del miedo IV', 'Darren Lynn Bousman', '2017-05-18 09:52:10', ' Tobin Bell, Scott Patterson, Costas Mandylor | See full cast & crew', 'Despite Jigsaw\'s death, and in order to save the lives of two of his colleagues, Lieutenant Rigg is forced to take part in a new game, which promises to test him to the limit.', '1', 'img/sawiv.jpg');
INSERT INTO `peliculas` VALUES ('3', '\r\nEl juego del miedo V', 'David Hackl', '2017-05-18 09:53:42', ' Scott Patterson, Costas Mandylor, Tobin Bell | See full cast & crew', 'Following Jigsaw\'s grisly demise, Mark Hoffman is commended as a hero, but Agent Strahm is suspicious, and delves into Hoffman\'s past. Meanwhile, another group of people are put through a series of gruesome tests.', '1', 'img/sawv.jpg');
INSERT INTO `peliculas` VALUES ('4', 'Ángeles y demonios ', 'Ron Howard', '2010-05-18 09:54:57', ' Tom Hanks, Ewan McGregor, Ayelet Zurer | See full cast & crew', 'Harvard symbologist Robert Langdon works with a nuclear physicist to solve a murder and prevent a terrorist act against the Vatican during one of the significant events within the church.', '2', 'img/angelsanddemons.jpg');
INSERT INTO `peliculas` VALUES ('5', 'Capitan America', 'Joe Johnston', '2017-01-30 09:56:25', 'Joe Johnston', ' Chris Evans, Hugo Weaving, Samuel L. Jackson', '2', 'img/captainamerica.jpg');
INSERT INTO `peliculas` VALUES ('6', 'Gladiador', ' Ridley Scott', '2017-05-09 09:57:33', ' Russell Crowe, Joaquin Phoenix, Connie Nielsen', 'When a Roman general is betrayed and his family murdered by an emperor\'s corrupt son, he comes to Rome as a gladiator to seek revenge.', '2', 'img/gladiator.jpg');
INSERT INTO `peliculas` VALUES ('7', 'Toy Story 3', ' Lee Unkrich', '2010-05-18 09:58:17', ' Tom Hanks, Tim Allen, Joan Cusack ', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it\'s up to Woody to convince the other toys that they weren\'t abandoned and to return home.', '3', 'img/toystory3.jpg');
INSERT INTO `peliculas` VALUES ('8', 'madagascar 2', 'Eric Darnell, Tom McGrath', '2017-01-27 09:59:16', ' Ben Stiller, Chris Rock, David Schwimmer', 'The animals try to fly back to New York City, but crash-land on an African wildlife refuge, where Alex is reunited with his parents.', '3', 'img/madagascar.jpg');


-- -----------------------------------------------------
-- Table `peliculas_has_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `peliculas_has_usuarios`;
CREATE TABLE IF NOT EXISTS `peliculas_has_usuarios` (
  `id_peliculas_has_usuarioscol` INT NOT NULL AUTO_INCREMENT,
  `fk_peliculas_id` INT(10) UNSIGNED NOT NULL,
  `fk_usuarios_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_peliculas_has_usuarioscol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `fk_abonado_premium` TINYINT NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


CREATE UNIQUE INDEX `id` USING BTREE ON `usuarios` (`id`);
INSERT INTO `usuarios` VALUES ('1', 'Matias', 'admin', 'Matias', 'matias.lopeztraynor@davinci.edu.ar', 'MD5('1234')');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;